[package]
name = "cogrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
serde_yaml = "0.9.34"
serde = { version = "1.0.217", features = ["derive"] }
